name: Containers Deployment via SSM
on: 
  push:
    branches: ["main"]
jobs:
  deploy: #배포정보
    name: 배포 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4

      - name: AWS 자격 확인
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy container via SSM
        run: |
          aws ssm send-command \
              --instance-ids "i-0374d6048a9230a9c"\
              --document-name "AWS-RunShellScript" \
              --parameters "commands=[
                  'sudo docker stop nginx-container || true',
                  'sudo docker rm nginx-container || true',
                  'sudo docker run -d --name nginx-container -p 80:80 nginx:latest'                  
                              
              ]" \
              --region ${{ secrets.AWS_REGION }} \
              --comment "Deploying container via SSM"