name: Containers Deployment via SSM
on: 
  push:
    branches: ["main"]
jobs:
  deploy: #배포정보
    name: 배포 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4

      - name: AWS 자격 확인
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy from S3 to EC2 using SSM
        run: |
          aws ssm send-command \
              --document-name "AWS-RunShellScript" \
              --parameters "commands=[
                  \"sudo aws s3 sync s3://${{ secrets.S3_BUCKET_NAME }}/html/ /usr/share/nginx/html/ --delete\",
                  \"sudo chown -R ec2-user:nginx /usr/share/nginx/html/\",
                  \"sudo systemctl reload nginx\"            
              ]" \
              --region ${{ secrets.AWS_REGION }} \
              --comment "Deploying website from S3 to EC2"